"""initial tables

Revision ID: 04ad09468ff2
Revises: 
Create Date: 2026-01-16 00:38:42.668451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '04ad09468ff2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('track_ids', sqlite.JSON(), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index('ix_playlists_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_playlists_name', ['name'], unique=False)
        batch_op.create_index('ix_playlists_source_source_id', ['source', 'source_id'], unique=True)

    op.create_table('sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_duration_min', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('energy_curve', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index('ix_sets_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sets_name', ['name'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artists', sqlite.JSON(), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('key', sa.String(length=3), nullable=False),
    sa.Column('camelot', sa.String(length=3), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('mood', sqlite.JSON(), nullable=False),
    sa.Column('genre', sqlite.JSON(), nullable=False),
    sa.Column('vocals', sa.String(length=10), nullable=False),
    sa.Column('structure', sqlite.JSON(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index('ix_tracks_bpm', ['bpm'], unique=False)
        batch_op.create_index('ix_tracks_camelot', ['camelot'], unique=False)
        batch_op.create_index('ix_tracks_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_tracks_energy', ['energy'], unique=False)
        batch_op.create_index('ix_tracks_key', ['key'], unique=False)
        batch_op.create_index('ix_tracks_source_source_id', ['source', 'source_id'], unique=True)

    op.create_table('set_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('transition_type', sa.String(length=10), nullable=False),
    sa.Column('mix_in_point_ms', sa.Integer(), nullable=True),
    sa.Column('mix_out_point_ms', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('set_tracks', schema=None) as batch_op:
        batch_op.create_index('ix_set_tracks_set_id_position', ['set_id', 'position'], unique=True)
        batch_op.create_index('ix_set_tracks_track_id', ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_set_tracks_track_id')
        batch_op.drop_index('ix_set_tracks_set_id_position')

    op.drop_table('set_tracks')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_tracks_source_source_id')
        batch_op.drop_index('ix_tracks_key')
        batch_op.drop_index('ix_tracks_energy')
        batch_op.drop_index('ix_tracks_created_at')
        batch_op.drop_index('ix_tracks_camelot')
        batch_op.drop_index('ix_tracks_bpm')

    op.drop_table('tracks')
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index('ix_sets_name')
        batch_op.drop_index('ix_sets_created_at')

    op.drop_table('sets')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index('ix_playlists_source_source_id')
        batch_op.drop_index('ix_playlists_name')
        batch_op.drop_index('ix_playlists_created_at')

    op.drop_table('playlists')
    # ### end Alembic commands ###
