#!/usr/bin/env python3
"""
Обновление M3U8 с расширенными метаданными для DJ Pro AI
Включает: BPM, Key, Camelot, Energy Level, Genre, Loudness
"""

import json
import logging
from pathlib import Path

# Настройка логирования
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s | %(levelname)-8s | %(message)s", datefmt="%H:%M:%S"
)
logger = logging.getLogger(__name__)

PROJECT_DIR = Path(__file__).parent
DJ_SET_DIR = PROJECT_DIR / "dj_set_techno_2025"
METADATA_FILE = DJ_SET_DIR / "tracklist_metadata.json"


def generate_extended_m3u8(tracks, output_file):
    """Генерация расширенного M3U8 с полными метаданными"""
    lines = ["#EXTM3U"]
    lines.append("# Generated by Yandex Music Downloader + DJ Tools")
    lines.append("# Format: Extended M3U8 for DJ Pro AI / djay Pro")
    lines.append("")

    for track in tracks:
        # Стандартный EXTINF
        duration_sec = int(track["duration_ms"] / 1000) if track.get("duration_ms") else 0
        artist_title = f"{track['artist']} - {track['title']}"
        lines.append(f"#EXTINF:{duration_sec},{artist_title}")

        # Расширенные теги
        if track.get("genre"):
            lines.append(f"#EXTGENRE:{track['genre']}")

        if track.get("bpm"):
            lines.append(f"#EXTBPM:{track['bpm']}")

        if track.get("key"):
            lines.append(f"#EXTKEY:{track['key']}")

        if track.get("camelot"):
            lines.append(f"#EXTCAMELOT:{track['camelot']}")

        if track.get("energy"):
            lines.append(f"#EXTENERGY:{track['energy']}")

        if track.get("energy_category"):
            lines.append(f"#EXTENERGYCATEGORY:{track['energy_category']}")

        if track.get("loudness_lufs") is not None:
            lines.append(f"#EXTLOUDNESS:{track['loudness_lufs']}")

        if track.get("label"):
            lines.append(f"#EXTLABEL:{track['label']}")

        if track.get("key_confidence"):
            lines.append(f"#EXTKEYCONFIDENCE:{track['key_confidence']}")

        # Имя файла
        lines.append(track["filename"])
        lines.append("")  # Пустая строка между треками

    return "\n".join(lines)


# ============================================================================
# MAIN
# ============================================================================

logger.info("=" * 70)
logger.info("📝 M3U8 EXTENDED UPDATE")
logger.info("=" * 70)

# Загрузка метаданных
logger.info(f"\n📋 Загрузка метаданных из {METADATA_FILE}...")
with open(METADATA_FILE, encoding="utf-8") as f:
    data = json.load(f)
    tracks = data["tracks"]

logger.info(f"✓ Загружено {len(tracks)} треков")

# Проверка доступных полей
fields_stats = {
    "bpm": sum(1 for t in tracks if t.get("bpm")),
    "key": sum(1 for t in tracks if t.get("key")),
    "camelot": sum(1 for t in tracks if t.get("camelot")),
    "energy": sum(1 for t in tracks if t.get("energy")),
    "loudness_lufs": sum(1 for t in tracks if t.get("loudness_lufs") is not None),
}

logger.info("\n📊 Доступные метаданные:")
for field, count in fields_stats.items():
    percentage = (count / len(tracks)) * 100
    logger.info(f"  {field:15} {count:2d}/{len(tracks)} ({percentage:5.1f}%)")

# Генерация расширенного M3U8
logger.info("\n🎛️  Генерация расширенного M3U8...")
m3u8_content = generate_extended_m3u8(tracks, None)

# Сохранение основного M3U8
main_m3u8 = DJ_SET_DIR / "techno_2025_extended.m3u8"
with open(main_m3u8, "w", encoding="utf-8") as f:
    f.write(m3u8_content)

logger.info(f"✓ Основной M3U8: {main_m3u8}")

# Также обновим оригинальный файл
original_m3u8 = DJ_SET_DIR / "techno_2025.m3u8"
with open(original_m3u8, "w", encoding="utf-8") as f:
    f.write(m3u8_content)

logger.info(f"✓ Обновлен оригинальный: {original_m3u8}")

# Статистика
logger.info("\n" + "=" * 70)
logger.info("📊 СТАТИСТИКА M3U8")
logger.info("=" * 70)
logger.info(f"Треков в плейлисте: {len(tracks)}")
logger.info(f"Размер файла: {len(m3u8_content)} символов")
logger.info(f"Строк: {len(m3u8_content.splitlines())}")
logger.info("")
logger.info("Поддерживаемые теги:")
logger.info("  • #EXTINF - длительность и название")
logger.info("  • #EXTGENRE - жанр")
logger.info("  • #EXTBPM - темп (BPM)")
logger.info("  • #EXTKEY - музыкальный ключ")
logger.info("  • #EXTCAMELOT - Camelot Wheel код")
logger.info("  • #EXTENERGY - уровень энергии (1-10)")
logger.info("  • #EXTENERGYCATEGORY - категория энергии")
logger.info("  • #EXTLOUDNESS - громкость (LUFS)")
logger.info("  • #EXTLABEL - лейбл")
logger.info("  • #EXTKEYCONFIDENCE - уверенность в Key detection")
logger.info("=" * 70)

logger.info("\n✨ M3U8 успешно обновлен!")
logger.info("   Готов к импорту в DJ Pro AI / djay Pro / Rekordbox")
